[tool.poetry]
name = "poetry-demo1"
version = "0.1.0"
description = ""
authors = ["Krzysztof Piszcz <kpiszcz@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
